/**
 * Карты поля боя.
 */

import {MapConfig} from "./Types.ts";
import {MapObjectType as o, FoeType as f} from "./Enums.ts";

export const Maps:Readonly<MapConfig[]> = [
    // Уровень 1
    {
        size: {x:13, y:13},
        objects: [
            {objectType:o.spawnFoe, location:{x:0, y:0}},
            {objectType:o.spawnFoe, location:{x:6, y:0}},
            {objectType:o.spawnFoe, location:{x:12, y:0}},
            {objectType:o.spawnFirstPlayer, location:{x:4, y:12}},
            {objectType:o.spawnSecondPlayer, location:{x:8, y:12}},
            {objectType:o.eagle, location:{x:6, y:12}},
            {objectType:o.brick, location:{x:5, y:12}},
            {objectType:o.brick, location:{x:5, y:11}},
            {objectType:o.brick, location:{x:6, y:11}},
            {objectType:o.brick, location:{x:7, y:11}},
            {objectType:o.brick, location:{x:7, y:12}},

            {objectType:o.brick, location:{x:1, y:1}},
            {objectType:o.brick, location:{x:1, y:2}},
            {objectType:o.brick, location:{x:1, y:3}},
            {objectType:o.brick, location:{x:1, y:4}},
            {objectType:o.brick, location:{x:3, y:1}},
            {objectType:o.brick, location:{x:3, y:2}},
            {objectType:o.brick, location:{x:3, y:3}},
            {objectType:o.brick, location:{x:3, y:4}},
            {objectType:o.brick, location:{x:5, y:1}},
            {objectType:o.brick, location:{x:5, y:2}},
            {objectType:o.brick, location:{x:5, y:3}},
            {objectType:o.ceramic, location:{x:6, y:3}},
            {objectType:o.brick, location:{x:7, y:1}},
            {objectType:o.brick, location:{x:7, y:2}},
            {objectType:o.brick, location:{x:7, y:3}},
            {objectType:o.brick, location:{x:9, y:1}},
            {objectType:o.brick, location:{x:9, y:2}},
            {objectType:o.brick, location:{x:9, y:3}},
            {objectType:o.brick, location:{x:9, y:4}},
            {objectType:o.brick, location:{x:11, y:1}},
            {objectType:o.brick, location:{x:11, y:2}},
            {objectType:o.brick, location:{x:11, y:3}},
            {objectType:o.brick, location:{x:11, y:4}},
            {objectType:o.ceramic, location:{x:0, y:6}},
            {objectType:o.ceramic, location:{x:12, y:6}},
            {objectType:o.brick, location:{x:2, y:6}},
            {objectType:o.brick, location:{x:3, y:6}},
            {objectType:o.brick, location:{x:9, y:6}},
            {objectType:o.brick, location:{x:10, y:6}},
            {objectType:o.brick, location:{x:1, y:8}},
            {objectType:o.brick, location:{x:1, y:9}},
            {objectType:o.brick, location:{x:1, y:10}},
            {objectType:o.brick, location:{x:1, y:11}},
            {objectType:o.brick, location:{x:3, y:8}},
            {objectType:o.brick, location:{x:3, y:9}},
            {objectType:o.brick, location:{x:3, y:10}},
            {objectType:o.brick, location:{x:3, y:11}},
            {objectType:o.brick, location:{x:9, y:8}},
            {objectType:o.brick, location:{x:9, y:9}},
            {objectType:o.brick, location:{x:9, y:10}},
            {objectType:o.brick, location:{x:9, y:11}},
            {objectType:o.brick, location:{x:11, y:8}},
            {objectType:o.brick, location:{x:11, y:9}},
            {objectType:o.brick, location:{x:11, y:10}},
            {objectType:o.brick, location:{x:11, y:11}},
            {objectType:o.brick, location:{x:5, y:7}},
            {objectType:o.brick, location:{x:5, y:8}},
            {objectType:o.brick, location:{x:5, y:9}},
            {objectType:o.brick, location:{x:7, y:7}},
            {objectType:o.brick, location:{x:7, y:8}},
            {objectType:o.brick, location:{x:7, y:9}},
            {objectType:o.brick, location:{x:6, y:8}}
        ],
        foes: [
            f.simple, f.simple, f.simple, f.fast, f.fast,
            f.simple, f.simple, f.simple, f.rapid, f.rapid,
            f.simple, f.fast, f.simple, f.armor, f.simple,
            f.fast, f.rapid, f.fast, f.armor, f.armor
        ]
    },
    // Уровень 2
    {
        size: {x:13, y:13},
        objects: [
            {objectType:o.spawnFoe, location:{x:0, y:0}},
            {objectType:o.spawnFoe, location:{x:6, y:0}},
            {objectType:o.spawnFoe, location:{x:12, y:0}},
            {objectType:o.spawnFirstPlayer, location:{x:4, y:12}},
            {objectType:o.spawnSecondPlayer, location:{x:8, y:12}},
            {objectType:o.eagle, location:{x:6, y:12}},
            {objectType:o.brick, location:{x:5, y:12}},
            {objectType:o.brick, location:{x:5, y:11}},
            {objectType:o.brick, location:{x:6, y:11}},
            {objectType:o.brick, location:{x:7, y:11}},
            {objectType:o.brick, location:{x:7, y:12}},

            {objectType:o.ceramic, location:{x:3, y:0}},
            {objectType:o.ceramic, location:{x:7, y:0}},
            {objectType:o.brick, location:{x:1, y:1}},
            {objectType:o.ceramic, location:{x:3, y:1}},
            {objectType:o.brick, location:{x:7, y:1}},
            {objectType:o.brick, location:{x:9, y:1}},
            {objectType:o.brick, location:{x:11, y:1}},
            {objectType:o.brick, location:{x:1, y:2}},
            {objectType:o.brick, location:{x:6, y:2}},
            {objectType:o.brick, location:{x:7, y:2}},
            {objectType:o.brick, location:{x:9, y:2}},
            {objectType:o.ceramic, location:{x:10, y:2}},
            {objectType:o.brick, location:{x:11, y:2}},
            {objectType:o.brick, location:{x:3, y:3}},
            {objectType:o.ceramic, location:{x:9, y:3}},
            {objectType:o.bush, location:{x:0, y:4}},
            {objectType:o.brick, location:{x:3, y:4}},
            {objectType:o.ceramic, location:{x:6, y:4}},
            {objectType:o.brick, location:{x:9, y:4}},
            {objectType:o.bush, location:{x:10, y:4}},
            {objectType:o.brick, location:{x:11, y:4}},
            {objectType:o.ceramic, location:{x:12, y:4}},
            {objectType:o.bush, location:{x:0, y:5}},
            {objectType:o.bush, location:{x:1, y:5}},
            {objectType:o.brick, location:{x:5, y:5}},
            {objectType:o.ceramic, location:{x:8, y:5}},
            {objectType:o.bush, location:{x:10, y:5}},
            {objectType:o.brick, location:{x:1, y:6}},
            {objectType:o.brick, location:{x:2, y:6}},
            {objectType:o.brick, location:{x:3, y:6}},
            {objectType:o.bush, location:{x:4, y:6}},
            {objectType:o.bush, location:{x:5, y:6}},
            {objectType:o.bush, location:{x:6, y:6}},
            {objectType:o.ceramic, location:{x:7, y:6}},
            {objectType:o.bush, location:{x:10, y:6}},
            {objectType:o.brick, location:{x:11, y:6}},
            {objectType:o.ceramic, location:{x:3, y:7}},
            {objectType:o.bush, location:{x:4, y:7}},
            {objectType:o.brick, location:{x:5, y:7}},
            {objectType:o.brick, location:{x:7, y:7}},
            {objectType:o.brick, location:{x:9, y:7}},
            {objectType:o.brick, location:{x:11, y:7}},
            {objectType:o.ceramic, location:{x:0, y:8}},
            {objectType:o.brick, location:{x:1, y:8}},
            {objectType:o.ceramic, location:{x:3, y:8}},
            {objectType:o.brick, location:{x:5, y:8}},
            {objectType:o.brick, location:{x:7, y:8}},
            {objectType:o.brick, location:{x:11, y:8}},
            {objectType:o.brick, location:{x:1, y:9}},
            {objectType:o.brick, location:{x:3, y:9}},
            {objectType:o.brick, location:{x:5, y:9}},
            {objectType:o.brick, location:{x:6, y:9}},
            {objectType:o.brick, location:{x:7, y:9}},
            {objectType:o.brick, location:{x:9, y:9}},
            {objectType:o.ceramic, location:{x:10, y:9}},
            {objectType:o.brick, location:{x:11, y:9}},
            {objectType:o.brick, location:{x:1, y:10}},
            {objectType:o.brick, location:{x:3, y:10}},
            {objectType:o.brick, location:{x:5, y:10}},
            {objectType:o.brick, location:{x:6, y:10}},
            {objectType:o.brick, location:{x:7, y:10}},
            {objectType:o.brick, location:{x:1, y:11}},
            {objectType:o.brick, location:{x:9, y:11}},
            {objectType:o.brick, location:{x:11, y:11}},
            {objectType:o.brick, location:{x:1, y:12}},
            {objectType:o.brick, location:{x:3, y:12}},
            {objectType:o.brick, location:{x:9, y:12}},
            {objectType:o.brick, location:{x:10, y:12}},
            {objectType:o.brick, location:{x:11, y:12}}
        ],
        foes: [
            f.simple, f.fast, f.rapid, f.fast, f.simple,
            f.simple, f.armor, f.fast, f.rapid, f.simple,
            f.armor, f.rapid, f.simple, f.rapid, f.armor,
            f.rapid, f.fast, f.armor, f.armor, f.rapid
        ]
    },
    // Уровень 3
    {
        size: {x:13, y:13},
        objects: [
            {objectType:o.spawnFoe, location:{x:0, y:0}},
            {objectType:o.spawnFoe, location:{x:6, y:0}},
            {objectType:o.spawnFoe, location:{x:12, y:0}},
            {objectType:o.spawnFirstPlayer, location:{x:4, y:12}},
            {objectType:o.spawnSecondPlayer, location:{x:8, y:12}},
            {objectType:o.eagle, location:{x:6, y:12}},
            {objectType:o.brick, location:{x:5, y:12}},
            {objectType:o.brick, location:{x:5, y:11}},
            {objectType:o.brick, location:{x:6, y:11}},
            {objectType:o.brick, location:{x:7, y:11}},
            {objectType:o.brick, location:{x:7, y:12}},
            
            {objectType:o.brick, location:{x:4, y:0}},
            {objectType:o.brick, location:{x:8, y:0}},
            {objectType:o.bush, location:{x:1, y:1}},
            {objectType:o.bush, location:{x:2, y:1}},
            {objectType:o.bush, location:{x:3, y:1}},
            {objectType:o.brick, location:{x:4, y:1}},
            {objectType:o.ceramic, location:{x:10, y:1}},
            {objectType:o.ceramic, location:{x:11, y:1}},
            {objectType:o.ceramic, location:{x:12, y:1}},
            {objectType:o.brick, location:{x:0, y:2}},
            {objectType:o.bush, location:{x:1, y:2}},
            {objectType:o.bush, location:{x:2, y:2}},
            {objectType:o.bush, location:{x:3, y:2}},
            {objectType:o.bush, location:{x:0, y:3}},
            {objectType:o.bush, location:{x:1, y:3}},
            {objectType:o.bush, location:{x:2, y:3}},
            {objectType:o.bush, location:{x:3, y:3}},
            {objectType:o.brick, location:{x:7, y:3}},
            {objectType:o.brick, location:{x:9, y:3}},
            {objectType:o.brick, location:{x:10, y:3}},
            {objectType:o.brick, location:{x:11, y:3}},
            {objectType:o.brick, location:{x:12, y:3}},
            {objectType:o.bush, location:{x:0, y:4}},
            {objectType:o.bush, location:{x:1, y:4}},
            {objectType:o.bush, location:{x:2, y:4}},
            {objectType:o.bush, location:{x:3, y:4}},
            {objectType:o.brick, location:{x:4, y:4}},
            {objectType:o.brick, location:{x:5, y:4}},
            {objectType:o.brick, location:{x:6, y:4}},
            {objectType:o.brick, location:{x:7, y:4}},
            {objectType:o.brick, location:{x:9, y:4}},
            {objectType:o.brick, location:{x:11, y:4}},
            {objectType:o.bush, location:{x:0, y:5}},
            {objectType:o.bush, location:{x:1, y:5}},
            {objectType:o.bush, location:{x:2, y:5}},
            {objectType:o.bush, location:{x:3, y:5}},
            {objectType:o.brick, location:{x:6, y:5}},
            {objectType:o.brick, location:{x:11, y:5}},
            {objectType:o.bush, location:{x:1, y:6}},
            {objectType:o.ceramic, location:{x:6, y:6}},
            {objectType:o.ceramic, location:{x:7, y:6}},
            {objectType:o.ceramic, location:{x:8, y:6}},
            {objectType:o.bush, location:{x:11, y:6}},
            {objectType:o.brick, location:{x:1, y:7}},
            {objectType:o.brick, location:{x:3, y:7}},
            {objectType:o.bush, location:{x:9, y:7}},
            {objectType:o.bush, location:{x:10, y:7}},
            {objectType:o.bush, location:{x:11, y:7}},
            {objectType:o.bush, location:{x:12, y:7}},
            {objectType:o.brick, location:{x:1, y:8}},
            {objectType:o.brick, location:{x:3, y:8}},
            {objectType:o.brick, location:{x:5, y:8}},
            {objectType:o.brick, location:{x:7, y:8}},
            {objectType:o.brick, location:{x:8, y:8}},
            {objectType:o.bush, location:{x:9, y:8}},
            {objectType:o.bush, location:{x:10, y:8}},
            {objectType:o.bush, location:{x:11, y:8}},
            {objectType:o.bush, location:{x:12, y:8}},
            {objectType:o.brick, location:{x:5, y:9}},
            {objectType:o.brick, location:{x:7, y:9}},
            {objectType:o.brick, location:{x:8, y:9}},
            {objectType:o.bush, location:{x:9, y:9}},
            {objectType:o.bush, location:{x:10, y:9}},
            {objectType:o.bush, location:{x:11, y:9}},
            {objectType:o.bush, location:{x:12, y:9}},
            {objectType:o.brick, location:{x:0, y:10}},
            {objectType:o.ceramic, location:{x:3, y:10}},
            {objectType:o.brick, location:{x:8, y:10}},
            {objectType:o.bush, location:{x:9, y:10}},
            {objectType:o.bush, location:{x:10, y:10}},
            {objectType:o.bush, location:{x:11, y:10}},
            {objectType:o.brick, location:{x:0, y:11}},
            {objectType:o.brick, location:{x:1, y:11}},
            {objectType:o.ceramic, location:{x:3, y:11}},
            {objectType:o.bush, location:{x:9, y:11}},
            {objectType:o.bush, location:{x:10, y:11}},
            {objectType:o.bush, location:{x:11, y:11}},
            {objectType:o.ceramic, location:{x:0, y:12}},
            {objectType:o.brick, location:{x:1, y:12}},
            {objectType:o.brick, location:{x:2, y:12}},
            {objectType:o.brick, location:{x:9, y:12}}
        ],
        foes: [
            f.simple, f.fast, f.simple, f.fast, f.simple,
            f.armor, f.rapid, f.fast, f.armor, f.simple,
            f.fast, f.armor, f.rapid, f.simple, f.fast,
            f.armor, f.fast, f.rapid, f.armor, f.simple
        ]
    },
    // Уровень 4
    {
        size: {x:13, y:13},
        objects: [
            {objectType:o.spawnFoe, location:{x:0, y:0}},
            {objectType:o.spawnFoe, location:{x:6, y:0}},
            {objectType:o.spawnFoe, location:{x:12, y:0}},
            {objectType:o.spawnFirstPlayer, location:{x:4, y:12}},
            {objectType:o.spawnSecondPlayer, location:{x:8, y:12}},
            {objectType:o.eagle, location:{x:6, y:12}},
            {objectType:o.brick, location:{x:5, y:12}},
            {objectType:o.brick, location:{x:5, y:11}},
            {objectType:o.brick, location:{x:6, y:11}},
            {objectType:o.brick, location:{x:7, y:11}},
            {objectType:o.brick, location:{x:7, y:12}},
            
            {objectType:o.bush, location:{x:1, y:0}},
            {objectType:o.bush, location:{x:2, y:0}},
            {objectType:o.bush, location:{x:11, y:0}},
            {objectType:o.bush, location:{x:0, y:1}},
            {objectType:o.bush, location:{x:1, y:1}},
            {objectType:o.brick, location:{x:5, y:1}},
            {objectType:o.brick, location:{x:6, y:1}},
            {objectType:o.bush, location:{x:12, y:1}},
            {objectType:o.bush, location:{x:0, y:2}},
            {objectType:o.brick, location:{x:4, y:2}},
            {objectType:o.brick, location:{x:5, y:2}},
            {objectType:o.brick, location:{x:6, y:2}},
            {objectType:o.brick, location:{x:7, y:2}},
            {objectType:o.brick, location:{x:8, y:2}},
            {objectType:o.ceramic, location:{x:12, y:2}},
            {objectType:o.ceramic, location:{x:0, y:3}},
            {objectType:o.brick, location:{x:3, y:3}},
            {objectType:o.brick, location:{x:4, y:3}},
            {objectType:o.brick, location:{x:5, y:3}},
            {objectType:o.brick, location:{x:6, y:3}},
            {objectType:o.brick, location:{x:7, y:3}},
            {objectType:o.brick, location:{x:8, y:3}},
            {objectType:o.brick, location:{x:9, y:3}},
            {objectType:o.brick, location:{x:10, y:3}},
            {objectType:o.brick, location:{x:2, y:4}},
            {objectType:o.brick, location:{x:3, y:4}},
            {objectType:o.brick, location:{x:7, y:4}},
            {objectType:o.brick, location:{x:8, y:4}},
            {objectType:o.brick, location:{x:10, y:4}},
            {objectType:o.water, location:{x:0, y:5}},
            {objectType:o.brick, location:{x:2, y:5}},
            {objectType:o.ceramic, location:{x:4, y:5}},
            {objectType:o.ceramic, location:{x:6, y:5}},
            {objectType:o.brick, location:{x:8, y:5}},
            {objectType:o.brick, location:{x:2, y:6}},
            {objectType:o.brick, location:{x:8, y:6}},
            {objectType:o.water, location:{x:11, y:6}},
            {objectType:o.water, location:{x:12, y:6}},
            {objectType:o.brick, location:{x:2, y:7}},
            {objectType:o.brick, location:{x:3, y:7}},
            {objectType:o.brick, location:{x:4, y:7}},
            {objectType:o.brick, location:{x:5, y:7}},
            {objectType:o.brick, location:{x:6, y:7}},
            {objectType:o.brick, location:{x:7, y:7}},
            {objectType:o.brick, location:{x:8, y:7}},
            {objectType:o.brick, location:{x:9, y:7}},
            {objectType:o.brick, location:{x:1, y:8}},
            {objectType:o.brick, location:{x:2, y:8}},
            {objectType:o.brick, location:{x:3, y:8}},
            {objectType:o.brick, location:{x:4, y:8}},
            {objectType:o.brick, location:{x:5, y:8}},
            {objectType:o.brick, location:{x:6, y:8}},
            {objectType:o.brick, location:{x:7, y:8}},
            {objectType:o.brick, location:{x:8, y:8}},
            {objectType:o.brick, location:{x:9, y:8}},
            {objectType:o.brick, location:{x:10, y:8}},
            {objectType:o.brick, location:{x:3, y:9}},
            {objectType:o.brick, location:{x:4, y:9}},
            {objectType:o.brick, location:{x:5, y:9}},
            {objectType:o.brick, location:{x:6, y:9}},
            {objectType:o.brick, location:{x:7, y:9}},
            {objectType:o.brick, location:{x:8, y:9}},
            {objectType:o.brick, location:{x:1, y:10}},
            {objectType:o.brick, location:{x:2, y:10}},
            {objectType:o.brick, location:{x:9, y:10}},
            {objectType:o.brick, location:{x:10, y:10}},
            {objectType:o.bush, location:{x:12, y:10}},
            {objectType:o.bush, location:{x:0, y:11}},
            {objectType:o.bush, location:{x:11, y:11}},
            {objectType:o.brick, location:{x:12, y:11}},
            {objectType:o.ceramic, location:{x:0, y:12}},
            {objectType:o.bush, location:{x:1, y:12}},
            {objectType:o.bush, location:{x:10, y:12}},
            {objectType:o.bush, location:{x:11, y:12}},
            {objectType:o.ceramic, location:{x:12, y:12}}
        ],
        foes: [
            f.fast, f.simple, f.rapid, f.simple, f.simple,
            f.rapid, f.armor, f.fast, f.rapid, f.armor,
            f.fast, f.simple, f.rapid, f.fast, f.simple,
            f.rapid, f.fast, f.simple, f.armor, f.fast
        ]
    },
    // Уровень 5
    {
        size: {x:13, y:13},
        objects: [
            {objectType:o.spawnFoe, location:{x:0, y:0}},
            {objectType:o.spawnFoe, location:{x:6, y:0}},
            {objectType:o.spawnFoe, location:{x:12, y:0}},
            {objectType:o.spawnFirstPlayer, location:{x:4, y:12}},
            {objectType:o.spawnSecondPlayer, location:{x:8, y:12}},
            {objectType:o.eagle, location:{x:6, y:12}},
            {objectType:o.brick, location:{x:5, y:12}},
            {objectType:o.brick, location:{x:5, y:11}},
            {objectType:o.brick, location:{x:6, y:11}},
            {objectType:o.brick, location:{x:7, y:11}},
            {objectType:o.brick, location:{x:7, y:12}},
            
            {objectType:o.brick, location:{x:4, y:0}},
            {objectType:o.brick, location:{x:5, y:0}},
            {objectType:o.ceramic, location:{x:0, y:1}},
            {objectType:o.brick, location:{x:2, y:1}},
            {objectType:o.brick, location:{x:4, y:1}},
            {objectType:o.ceramic, location:{x:8, y:1}},
            {objectType:o.ceramic, location:{x:9, y:1}},
            {objectType:o.ceramic, location:{x:10, y:1}},
            {objectType:o.ceramic, location:{x:0, y:2}},
            {objectType:o.brick, location:{x:2, y:2}},
            {objectType:o.brick, location:{x:6, y:2}},
            {objectType:o.brick, location:{x:0, y:3}},
            {objectType:o.brick, location:{x:2, y:3}},
            {objectType:o.brick, location:{x:3, y:3}},
            {objectType:o.brick, location:{x:4, y:3}},
            {objectType:o.brick, location:{x:6, y:3}},
            {objectType:o.brick, location:{x:7, y:3}},
            {objectType:o.water, location:{x:9, y:3}},
            {objectType:o.water, location:{x:10, y:3}},
            {objectType:o.water, location:{x:12, y:3}},
            {objectType:o.brick, location:{x:0, y:4}},
            {objectType:o.brick, location:{x:4, y:4}},
            {objectType:o.water, location:{x:9, y:4}},
            {objectType:o.brick, location:{x:2, y:5}},
            {objectType:o.water, location:{x:4, y:5}},
            {objectType:o.water, location:{x:5, y:5}},
            {objectType:o.water, location:{x:7, y:5}},
            {objectType:o.water, location:{x:8, y:5}},
            {objectType:o.water, location:{x:9, y:5}},
            {objectType:o.brick, location:{x:11, y:5}},
            {objectType:o.brick, location:{x:12, y:5}},
            {objectType:o.brick, location:{x:0, y:6}},
            {objectType:o.brick, location:{x:1, y:6}},
            {objectType:o.water, location:{x:4, y:6}},
            {objectType:o.brick, location:{x:5, y:6}},
            {objectType:o.brick, location:{x:7, y:6}},
            {objectType:o.brick, location:{x:8, y:6}},
            {objectType:o.water, location:{x:4, y:7}},
            {objectType:o.ceramic, location:{x:10, y:7}},
            {objectType:o.ceramic, location:{x:11, y:7}},
            {objectType:o.water, location:{x:0, y:8}},
            {objectType:o.water, location:{x:1, y:8}},
            {objectType:o.water, location:{x:2, y:8}},
            {objectType:o.water, location:{x:4, y:8}},
            {objectType:o.ceramic, location:{x:6, y:8}},
            {objectType:o.brick, location:{x:8, y:8}},
            {objectType:o.ceramic, location:{x:10, y:8}},
            {objectType:o.brick, location:{x:3, y:9}},
            {objectType:o.brick, location:{x:4, y:9}},
            {objectType:o.ceramic, location:{x:10, y:9}},
            {objectType:o.brick, location:{x:11, y:9}},
            {objectType:o.brick, location:{x:12, y:9}},
            {objectType:o.brick, location:{x:4, y:10}},
            {objectType:o.brick, location:{x:5, y:10}},
            {objectType:o.brick, location:{x:6, y:10}},
            {objectType:o.brick, location:{x:7, y:10}},
            {objectType:o.brick, location:{x:8, y:10}},
            {objectType:o.brick, location:{x:9, y:10}},
            {objectType:o.brick, location:{x:0, y:11}},
            {objectType:o.brick, location:{x:1, y:11}},
            {objectType:o.brick, location:{x:2, y:11}},
            {objectType:o.brick, location:{x:9, y:11}},
            {objectType:o.brick, location:{x:10, y:11}},
            {objectType:o.brick, location:{x:0, y:12}}
        ],
        foes: [
            f.rapid, f.armor, f.fast, f.simple, f.fast,
            f.armor, f.fast, f.simple, f.rapid, f.rapid,
            f.simple, f.simple, f.armor, f.simple, f.fast,
            f.simple, f.armor, f.armor, f.simple, f.simple
        ]
    },
    // Уровень 20
    {
        size: {x:13, y:13},
        objects: [
            {objectType:o.spawnFoe, location:{x:0, y:0}},
            {objectType:o.spawnFoe, location:{x:6, y:0}},
            {objectType:o.spawnFoe, location:{x:12, y:0}},
            {objectType:o.spawnFirstPlayer, location:{x:4, y:12}},
            {objectType:o.spawnSecondPlayer, location:{x:8, y:12}},
            {objectType:o.eagle, location:{x:6, y:12}},
            {objectType:o.brick, location:{x:5, y:12}},
            {objectType:o.brick, location:{x:5, y:11}},
            {objectType:o.brick, location:{x:6, y:11}},
            {objectType:o.brick, location:{x:7, y:11}},
            {objectType:o.brick, location:{x:7, y:12}},
            
            {objectType:o.water, location:{x:3, y:0}},
            {objectType:o.brick, location:{x:5, y:0}},
            {objectType:o.brick, location:{x:8, y:0}},
            {objectType:o.brick, location:{x:10, y:0}},
            {objectType:o.brick, location:{x:8, y:1}},
            {objectType:o.ceramic, location:{x:10, y:1}},
            {objectType:o.water, location:{x:3, y:2}},
            {objectType:o.brick, location:{x:5, y:2}},
            {objectType:o.ceramic, location:{x:6, y:2}},
            {objectType:o.brick, location:{x:8, y:2}},
            {objectType:o.brick, location:{x:10, y:2}},
            {objectType:o.ceramic, location:{x:0, y:3}},
            {objectType:o.brick, location:{x:2, y:3}},
            {objectType:o.water, location:{x:3, y:3}},
            {objectType:o.ceramic, location:{x:5, y:3}},
            {objectType:o.brick, location:{x:7, y:3}},
            {objectType:o.brick, location:{x:8, y:3}},
            {objectType:o.brick, location:{x:10, y:3}},
            {objectType:o.brick, location:{x:2, y:4}},
            {objectType:o.water, location:{x:3, y:4}},
            {objectType:o.brick, location:{x:7, y:4}},
            {objectType:o.brick, location:{x:0, y:5}},
            {objectType:o.brick, location:{x:2, y:5}},
            {objectType:o.water, location:{x:3, y:5}},
            {objectType:o.water, location:{x:4, y:5}},
            {objectType:o.water, location:{x:6, y:5}},
            {objectType:o.water, location:{x:7, y:5}},
            {objectType:o.water, location:{x:8, y:5}},
            {objectType:o.water, location:{x:9, y:5}},
            {objectType:o.brick, location:{x:12, y:5}},
            {objectType:o.brick, location:{x:3, y:6}},
            {objectType:o.bush, location:{x:7, y:6}},
            {objectType:o.water, location:{x:9, y:6}},
            {objectType:o.ceramic, location:{x:11, y:6}},
            {objectType:o.ceramic, location:{x:12, y:6}},
            {objectType:o.brick, location:{x:0, y:7}},
            {objectType:o.brick, location:{x:1, y:7}},
            {objectType:o.brick, location:{x:2, y:7}},
            {objectType:o.brick, location:{x:3, y:7}},
            {objectType:o.ceramic, location:{x:5, y:7}},
            {objectType:o.bush, location:{x:6, y:7}},
            {objectType:o.bush, location:{x:7, y:7}},
            {objectType:o.bush, location:{x:8, y:7}},
            {objectType:o.water, location:{x:9, y:7}},
            {objectType:o.brick, location:{x:11, y:7}},
            {objectType:o.brick, location:{x:12, y:7}},
            {objectType:o.brick, location:{x:0, y:8}},
            {objectType:o.brick, location:{x:2, y:8}},
            {objectType:o.brick, location:{x:5, y:8}},
            {objectType:o.bush, location:{x:6, y:8}},
            {objectType:o.bush, location:{x:7, y:8}},
            {objectType:o.bush, location:{x:8, y:8}},
            {objectType:o.water, location:{x:9, y:8}},
            {objectType:o.brick, location:{x:11, y:8}},
            {objectType:o.ceramic, location:{x:1, y:9}},
            {objectType:o.brick, location:{x:5, y:9}},
            {objectType:o.bush, location:{x:7, y:9}},
            {objectType:o.water, location:{x:9, y:9}},
            {objectType:o.bush, location:{x:11, y:9}},
            {objectType:o.brick, location:{x:1, y:10}},
            {objectType:o.ceramic, location:{x:3, y:10}},
            {objectType:o.brick, location:{x:5, y:10}},
            {objectType:o.brick, location:{x:6, y:10}},
            {objectType:o.brick, location:{x:7, y:10}},
            {objectType:o.bush, location:{x:10, y:10}},
            {objectType:o.bush, location:{x:11, y:10}},
            {objectType:o.bush, location:{x:12, y:10}},
            {objectType:o.brick, location:{x:1, y:11}},
            {objectType:o.brick, location:{x:3, y:11}},
            {objectType:o.water, location:{x:9, y:11}},
            {objectType:o.bush, location:{x:10, y:11}},
            {objectType:o.bush, location:{x:11, y:11}},
            {objectType:o.bush, location:{x:12, y:11}},
            {objectType:o.water, location:{x:9, y:12}},
            {objectType:o.bush, location:{x:11, y:12}}
        ],
        foes: [
            f.simple, f.fast, f.fast, f.rapid, f.simple,
            f.rapid, f.rapid, f.armor, f.fast, f.simple,
            f.armor, f.fast, f.fast, f.armor, f.rapid,
            f.rapid, f.simple, f.fast, f.fast, f.armor
        ]
    },
    // Уровень 24
    {
        size: {x:13, y:13},
        objects: [
            {objectType:o.spawnFoe, location:{x:0, y:0}},
            {objectType:o.spawnFoe, location:{x:6, y:0}},
            {objectType:o.spawnFoe, location:{x:12, y:0}},
            {objectType:o.spawnFirstPlayer, location:{x:4, y:12}},
            {objectType:o.spawnSecondPlayer, location:{x:8, y:12}},
            {objectType:o.eagle, location:{x:6, y:12}},
            {objectType:o.brick, location:{x:5, y:12}},
            {objectType:o.brick, location:{x:5, y:11}},
            {objectType:o.brick, location:{x:6, y:11}},
            {objectType:o.brick, location:{x:7, y:11}},
            {objectType:o.brick, location:{x:7, y:12}},
            
            {objectType:o.ceramic, location:{x:2, y:0}},
            {objectType:o.brick, location:{x:4, y:0}},
            {objectType:o.ceramic, location:{x:5, y:0}},
            {objectType:o.brick, location:{x:10, y:0}},
            {objectType:o.brick, location:{x:2, y:1}},
            {objectType:o.brick, location:{x:4, y:1}},
            {objectType:o.bush, location:{x:5, y:1}},
            {objectType:o.brick, location:{x:7, y:1}},
            {objectType:o.brick, location:{x:8, y:1}},
            {objectType:o.brick, location:{x:9, y:1}},
            {objectType:o.brick, location:{x:10, y:1}},
            {objectType:o.bush, location:{x:1, y:2}},
            {objectType:o.bush, location:{x:2, y:2}},
            {objectType:o.brick, location:{x:4, y:2}},
            {objectType:o.bush, location:{x:5, y:2}},
            {objectType:o.brick, location:{x:7, y:2}},
            {objectType:o.ceramic, location:{x:11, y:2}},
            {objectType:o.ceramic, location:{x:12, y:2}},
            {objectType:o.bush, location:{x:0, y:3}},
            {objectType:o.bush, location:{x:1, y:3}},
            {objectType:o.bush, location:{x:2, y:3}},
            {objectType:o.bush, location:{x:3, y:3}},
            {objectType:o.bush, location:{x:4, y:3}},
            {objectType:o.bush, location:{x:5, y:3}},
            {objectType:o.brick, location:{x:6, y:3}},
            {objectType:o.brick, location:{x:7, y:3}},
            {objectType:o.brick, location:{x:8, y:3}},
            {objectType:o.brick, location:{x:10, y:3}},
            {objectType:o.brick, location:{x:11, y:3}},
            {objectType:o.bush, location:{x:2, y:4}},
            {objectType:o.bush, location:{x:3, y:4}},
            {objectType:o.ceramic, location:{x:6, y:4}},
            {objectType:o.brick, location:{x:7, y:4}},
            {objectType:o.brick, location:{x:9, y:4}},
            {objectType:o.brick, location:{x:10, y:4}},
            {objectType:o.brick, location:{x:12, y:4}},
            {objectType:o.brick, location:{x:0, y:5}},
            {objectType:o.ceramic, location:{x:1, y:5}},
            {objectType:o.brick, location:{x:3, y:5}},
            {objectType:o.brick, location:{x:4, y:5}},
            {objectType:o.brick, location:{x:5, y:5}},
            {objectType:o.brick, location:{x:9, y:5}},
            {objectType:o.brick, location:{x:10, y:5}},
            {objectType:o.brick, location:{x:12, y:5}},
            {objectType:o.brick, location:{x:0, y:6}},
            {objectType:o.brick, location:{x:3, y:6}},
            {objectType:o.ice, location:{x:4, y:6}},
            {objectType:o.ice, location:{x:5, y:6}},
            {objectType:o.ice, location:{x:6, y:6}},
            {objectType:o.ice, location:{x:7, y:6}},
            {objectType:o.ice, location:{x:8, y:6}},
            {objectType:o.ice, location:{x:9, y:6}},
            {objectType:o.ice, location:{x:10, y:6}},
            {objectType:o.ice, location:{x:11, y:6}},
            {objectType:o.ice, location:{x:12, y:6}},
            {objectType:o.brick, location:{x:0, y:7}},
            {objectType:o.brick, location:{x:2, y:7}},
            {objectType:o.ice, location:{x:4, y:7}},
            {objectType:o.ice, location:{x:5, y:7}},
            {objectType:o.ice, location:{x:6, y:7}},
            {objectType:o.ice, location:{x:7, y:7}},
            {objectType:o.ice, location:{x:8, y:7}},
            {objectType:o.ice, location:{x:9, y:7}},
            {objectType:o.ice, location:{x:10, y:7}},
            {objectType:o.ice, location:{x:11, y:7}},
            {objectType:o.ice, location:{x:12, y:7}},
            {objectType:o.ceramic, location:{x:2, y:8}},
            {objectType:o.ice, location:{x:4, y:8}},
            {objectType:o.ice, location:{x:5, y:8}},
            {objectType:o.ice, location:{x:6, y:8}},
            {objectType:o.ice, location:{x:7, y:8}},
            {objectType:o.ice, location:{x:8, y:8}},
            {objectType:o.ice, location:{x:9, y:8}},
            {objectType:o.ice, location:{x:10, y:8}},
            {objectType:o.ice, location:{x:11, y:8}},
            {objectType:o.ice, location:{x:12, y:8}},
            {objectType:o.brick, location:{x:0, y:9}},
            {objectType:o.brick, location:{x:2, y:9}},
            {objectType:o.ice, location:{x:4, y:9}},
            {objectType:o.ice, location:{x:5, y:9}},
            {objectType:o.ice, location:{x:6, y:9}},
            {objectType:o.ice, location:{x:7, y:9}},
            {objectType:o.ice, location:{x:8, y:9}},
            {objectType:o.ice, location:{x:9, y:9}},
            {objectType:o.ice, location:{x:10, y:9}},
            {objectType:o.ice, location:{x:11, y:9}},
            {objectType:o.ice, location:{x:12, y:9}},
            {objectType:o.brick, location:{x:0, y:10}},
            {objectType:o.brick, location:{x:2, y:10}},
            {objectType:o.ice, location:{x:4, y:10}},
            {objectType:o.ice, location:{x:5, y:10}},
            {objectType:o.ice, location:{x:6, y:10}},
            {objectType:o.ice, location:{x:7, y:10}},
            {objectType:o.ice, location:{x:8, y:10}},
            {objectType:o.ice, location:{x:9, y:10}},
            {objectType:o.ice, location:{x:10, y:10}},
            {objectType:o.ice, location:{x:11, y:10}},
            {objectType:o.ice, location:{x:12, y:10}},
            {objectType:o.brick, location:{x:0, y:11}},
            {objectType:o.brick, location:{x:2, y:11}},
            {objectType:o.ice, location:{x:8, y:11}},
            {objectType:o.ice, location:{x:9, y:11}},
            {objectType:o.ice, location:{x:10, y:11}},
            {objectType:o.ice, location:{x:11, y:11}},
            {objectType:o.ice, location:{x:12, y:11}},
            {objectType:o.ice, location:{x:9, y:12}},
            {objectType:o.ice, location:{x:10, y:12}},
            {objectType:o.ice, location:{x:11, y:12}},
            {objectType:o.ice, location:{x:12, y:12}}
        ],
        foes: [
            f.rapid, f.fast, f.fast, f.fast, f.fast,
            f.armor, f.fast, f.rapid, f.simple, f.simple,
            f.fast, f.rapid, f.armor, f.rapid, f.simple,
            f.rapid, f.rapid, f.armor, f.armor, f.rapid
        ]
    }
];